dist: focal
language: c

matrix:
  include:
    - name: "linux-amd64-gcc-9"
      os: linux
      arch: amd64
      compiler: gcc-9
      env:
        - CXX="g++-9"
        - CFLAGS="-O2"
        - CXXFLAGS="-O2"
        - PKG_CC="gcc-9 g++-9"
    - name: "linux-ppc64le-gcc-9"
      os: linux
      arch: ppc64le
      compiler: gcc-9
      env:
        - CXX="g++-9"
        - CFLAGS="-O2"
        - CXXFLAGS="-O2"
        - PKG_CC="gcc-9 g++-9"
    - name: "linux-ppc64le-gcc-9-sw"
      os: linux
      arch: ppc64le
      compiler: gcc-9
      env:
        - CONFIGURE_OPTS="--with-cpu=no"
        - CXX="g++-9"
        - CFLAGS="-O2"
        - CXXFLAGS="-O2"
        - PKG_CC="gcc-9 g++-9"
    - name: "linux-s390x-gcc-9"
      os: linux
      arch: s390x
      compiler: gcc-9
      env:
        - CXX="g++-9"
        - CFLAGS="-O2"
        - CXXFLAGS="-O2"
        - PKG_CC="gcc-9 g++-9"
    - name: "linux-s390x-gcc-9-sw"
      os: linux
      arch: s390x
      compiler: gcc-9
      env:
        - CONFIGURE_OPTS="--with-cpu=no"
        - CXX="g++-9"
        - CFLAGS="-O2"
        - CXXFLAGS="-O2"
        - PKG_CC="gcc-9 g++-9"
    - name: "linux-amd64-gcc-10"
      os: linux
      arch: amd64
      compiler: gcc-10
      env:
        - CXX="g++-10"
        - CFLAGS="-O2"
        - CXXFLAGS="-O2"
        - PKG_CC="gcc-10 g++-10"
    - name: "linux-ppc64le-gcc-10"
      os: linux
      arch: ppc64le
      compiler: gcc-10
      env:
        - CXX="g++-10"
        - CFLAGS="-O2"
        - CXXFLAGS="-O2"
        - PKG_CC="gcc-10 g++-10"
    - name: "linux-ppc64le-gcc-10-sw"
      os: linux
      arch: ppc64le
      compiler: gcc-10
      env:
        - CONFIGURE_OPTS="--with-cpu=no"
        - CXX="g++-10"
        - CFLAGS="-O2"
        - CXXFLAGS="-O2"
        - PKG_CC="gcc-10 g++-10"
    - name: "linux-s390x-gcc-10"
      os: linux
      arch: s390x
      compiler: gcc-10
      env:
        - CXX="g++-10"
        - CFLAGS="-O2"
        - CXXFLAGS="-O2"
        - PKG_CC="gcc-10 g++-10"
    - name: "linux-s390x-gcc-10-sw"
      os: linux
      arch: s390x
      compiler: gcc-10
      env:
        - CONFIGURE_OPTS="--with-cpu=no"
        - CXX="g++-10"
        - CFLAGS="-O2"
        - CXXFLAGS="-O2"
        - PKG_CC="gcc-10 g++-10"

before_install:
  - sudo add-apt-repository universe
  - sudo apt-get update
  - sudo apt-get -y install ${PKG_CC}

script:
  - mkdir $(pwd)/install
  - ./configure $CONFIGURE_OPTS --prefix=$(pwd)/install
  - make -j $(nproc)
  - make install
  - make -j $(nproc) check
