name: libdfp CI on x86-64

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    permissions: {}
    strategy:
      matrix:
        node: [ubuntu-latest, ubuntu-24.04-s390x, ubuntu-24.04-ppc64le, ubuntu-24.04-ppc64le-p10]

    runs-on: ${{ matrix.node }}

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      with:
        persist-credentials: false

    - name: Configure libdfp
      env:
        GHA_NODE: ${{ matrix.node }}
      run: |
        mkdir build
        OPTS=""
        if [[ "$GHA_NODE" =~ "ppc64le-p10" ]]; then
          OPTS="$OPTS --with-cpu=power10"
        fi
        cd build
        ../configure $OPTS

    - name: Build libdfp
      working-directory: build
      run: make -j4

    - name: Run libdfp test suite
      working-directory: build
      run: make check -j4
